import Head from "next/head";
import Image from "next/image";
import React from "react";
import { PieChart } from "react-minimal-pie-chart";
import Sidebar from "./sidebar";
import Sidenav from "./sidenav";

const Card = (
  <div className="bg-white rounded-[8px] w-[262px] h-[200px] p-3">
    <p className="border-b-2 border-gray-100 p-3 flex gap-2">
      Average PR size{" "}
      <span className="border-2 rounded-full w-[19px] h-[19px] border-gray-200 text-[9px] justify-center items-center flex">
        i
      </span>
    </p>
    {/* Numbers */}
    <div className="flex justify-between p-4">
      <div className="flex flex-col gap-3">
        <div className="flex gap-4 justify-center items-center">
          <p className="text-[20px] font-bold">968</p>
          <p className="text-xs"> lines</p>
        </div>
        <p className="font-semibold">Line change </p>
        <p className="bg-[#4DBD981A] text-[#4DBD98] p-1 w-[63px] h-[30px] rounded flex align-center justify-center">
          24%
        </p>
      </div>
      <div className="flex flex-col gap-3">
        <div className="flex gap-4 justify-center items-center">
          <p className="text-[20px] font-bold">968</p>
          <p className="text-xs"> lines</p>
        </div>
        <p className="font-semibold">Line change </p>
      </div>
    </div>
  </div>
);
export default function Home() {
  return (
    <div className="w-full bg-white flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <Sidenav />
      <div className="bg-gray-100 w-[90%] h-[100vh] p-12">
        {/* Navbar */}
        <div className="flex justify-between w-[80%] mb-3">
          <h3 className="font-bold text-base">Project stats</h3>
          <div className="bg-white w-[125px] rounded-[8px] h-[44px] flex align-center justify-around">
            <span className="mt-3">All time</span>{" "}
            <svg
              width="10"
              height="5"
              viewBox="0 0 10 5"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
              className="mt-6"
            >
              <path d="M0 0L5 5L10 0H0Z" fill="#919AA3" />
            </svg>
          </div>
        </div>
        {/* Navbar close */}
        {/* Box Section */}
        <section className="flex justify-between  w-[80%]">
          {/* Box 1 */}
          <div className="flex flex-col gap-4">
            <div className="flex gap-4">
              {/* Card 1 */}
              {Card}
              {/* Card 2 */}
              {Card}
            </div>

            <div className="w-[540px] h-[286px] bg-white rounded-[8px] pb-10">
              <p className="border-b-2 border-gray-100 p-3 flex gap-2">
                Average PR size{" "}
                <span className="border-2 rounded-full w-[19px] h-[19px] border-gray-200 text-[9px] justify-center items-center flex">
                  i
                </span>
              </p>
              <div className="flex gap-4 justify-around mt-3">
                <div className="h-[170px] relative">
                  <PieChart
                    data={[
                      { title: "One", value: 10, color: "#E38627" },
                      { title: "Two", value: 15, color: "#C13C37" },
                      { title: "Three", value: 20, color: "#6A2135" },
                    ]}
                    lineWidth={22}
                  />
                  <div className="absolute bottom-10 left-10 flex flex-col justify-center items-center">
                    <p className="font-bold"> 17 hrs</p>
                    <p className="text-xs w-[110px]">
                      Average across 50 tickets in 4 weeks
                    </p>
                  </div>
                </div>
                <div className="flex flex-col gap-4">
                  <p className="flex gap-3">
                    <span className="bg-red-700 rounded-full w-4 h-4 mt-1"></span>
                    <span className=""> 4hrs Coding</span>
                  </p>
                  <p className="flex gap-3">
                    <span className="bg-red-700 rounded-full w-4 h-4 mt-1"></span>
                    <span className=""> 4hrs Coding</span>
                  </p>

                  <p className="flex gap-3">
                    <span className="bg-black rounded-full w-4 h-4 mt-1"></span>
                    <span className=""> 4hrs Coding</span>
                  </p>
                  <p className="flex gap-3">
                    <span className="bg-blue-700 rounded-full w-4 h-4 mt-1"></span>
                    <span className=""> 4hrs Coding</span>
                  </p>
                  <p className="flex gap-3">
                    <span className="bg-purple-700 rounded-full w-4 h-4 mt-1"></span>
                    <span className=""> 4hrs Coding</span>
                  </p>
                </div>
              </div>
              <div className="flex items-baseline ml-4 mb-1">
                <p className="bg-[#4DBD981A] text-[#4DBD98] p-1 w-[63px] h-[30px] rounded flex align-center justify-center ">
                  24%
                </p>
              </div>
            </div>
          </div>
          {/* Box 2 */}

          <div className="flex flex-col gap-3">
            {/* Card 1 */}

            <div className="w-[540px] h-[264px] bg-white rounded-[8px] pb-10 mt-1">
              <p className="border-b-2 border-gray-100 p-3 flex gap-2">
                Work breakdown{" "}
                <span className="border-2 rounded-full w-[19px] h-[19px] border-gray-200 text-[9px] justify-center items-center flex">
                  i
                </span>
              </p>
              <div className="flex items-start gap-4 p-3">
                <div className="flex gap-2 justify-center items-center">
                  <p className="text-[20px] font-bold">968</p>
                  <p className="text-xs"> lines</p>
                </div>
                <div className="flex gap-2 justify-center items-center">
                  <p className="text-[20px] font-bold">54</p>
                  <p className="text-xs"> tickets</p>
                </div>
                <div className="flex gap-2 justify-center items-center">
                  <p className="text-[20px] font-bold">4</p>
                  <p className="text-xs"> total weeks worked</p>
                </div>
              </div>
              <div className="flex p-3">
                <div className="w-32 h-8 bg-blue-700 rounded-l-2xl"></div>
                <div className="w-32 h-8 bg-orange-500"></div>
                <div className="w-32 h-8 bg-red-700"></div>
                <div className="w-32 h-8 bg-slate-700 rounded-r-2xl"></div>
              </div>
              <div className="grid grid-cols-2 p-3 gap-y-3">
                <p className="flex gap-3">
                  <span className="bg-red-700 rounded-full w-4 h-4 mt-1"></span>
                  <span className=""> 4hrs Coding</span>
                </p>
                <p className="flex gap-3">
                  <span className="bg-orange-400 rounded-full w-4 h-4 mt-1"></span>
                  <span className=""> 4hrs Coding</span>
                </p>
                <p className="flex gap-3">
                  <span className="bg-blue-700 rounded-full w-4 h-4 mt-1"></span>
                  <span className=""> 4hrs Coding</span>
                </p>
                <p className="flex gap-3">
                  <span className="bg-slate-700 rounded-full w-4 h-4 mt-1"></span>
                  <span className=""> 4hrs Coding</span>
                </p>
              </div>
            </div>

            {/* Card 2 */}
            <div className="w-[540px] h-[210px] bg-white rounded-[8px] pb-10">
              <div className="flex justify-between border-b-2 border-gray-100 p-2 mx-4">
                <p className="flex gap-2">
                  Idle Time Breakdown{" "}
                  <span className="border-2 rounded-full w-[19px] h-[19px] border-gray-200 text-[9px] justify-center items-center flex">
                    i
                  </span>
                </p>
                <div className="flex gap-3">
                  <p className="flex gap-3">
                    <span className="bg-slate-300 rounded-full w-4 h-4 mt-1"></span>
                    <span className=""> Idle</span>
                  </p>
                  <p className="flex gap-3">
                    <span className="bg-green-700 rounded-full w-4 h-4 mt-1"></span>
                    <span className=""> Productive</span>
                  </p>
                </div>
              </div>
              <div className="flex gap-12 items-center justify-center mt-6 border-b-2 border-[#03293D0D]">
                <div className="flex gap-1">
                <div className="w-9 h-24 rounded-t-md bg-slate-300 "></div>
                  <div className="w-9 h-16 bg-green-700 rounded-t-md mt-8"></div>
                </div>
                <div className="flex gap-1">
                <div className="w-9 h-16 rounded-t-md bg-slate-300 mt-8 "></div>
                  <div className="w-9 h-24 bg-green-700 rounded-t-md"></div>
                </div>
                <div className="flex gap-1">
                <div className="w-9 h-24 rounded-t-md bg-slate-300 "></div>
                  <div className="w-9 h-16 bg-green-700 rounded-t-md mt-8"></div>
                </div>
              </div>
              <div  className="flex gap-12 items-center justify-center text-sm text-[#03293D80]">
                    <p>Coding</p>
                    <p>Code review</p>
                    <p>QA review</p>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
